baseurl = "https://aeric.io"
title = "Happy New Year!"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = "yeaheo"
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 6 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "https://wx1.sinaimg.cn/large/b258d7f7ly1fy4y1k2z8bj21ja0lo128.jpg"
  SEOTitle = "吕啸腾的博客"
  description = "吕啸腾，运维开发工程师, 开源爱好者 | 这里是 吕啸腾 的博客，与你一起发现更大的世界。"
  keyword = "吕啸腾, lvxiaoteng, eric lv, Lvxiaoteng, 吕啸腾的网络日志, 吕啸腾的博客, Eric Blog, 博客, 个人网站, 互联网, Web, 云原生, PaaS, Istio, Kubernetes, 微服务, Microservice"
  slogan = "·越努力-越幸运·"

  image_404 = "img/404-bg.jpg"
  title_404 = "你来到了没有知识的荒原 :("

  # leancloud storage for page view counter
  page_view_conter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false 
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "运维开发工程师 | 开源爱好者"
  sidebar_avatar = "img/avatar-lvxiaoteng.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true
  featured_condition_size = 2 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  disqus_proxy = ""
  disqus_site = ""

  #wechat pay & alipay 
  reward = true

  [params.social]
  rss            = true 
  email          = "ihello.cn@gmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  twitter        = "https://twitter.com/EricLve"
  linkedin       = "https://www.linkedin.com/in/%E5%95%B8%E8%85%BE-%E5%90%95-371521176/"
  #stackoverflow  = "full profile url in stackoverflow"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/yeaheo"
  wechat         = "img/wechat/wechat.jpeg"
  weibo          = "https://weibo.cn/yeaheo"
  #pinterest     = "full profile url in pinterest"
  #medium        = "full profile url in medium"

  friends = true

  [[params.friend_link]]
  title = "Linda"
  href =  "https://zhaozhihan.com"

  bookmarks = true

  [[params.bookmark_link]]
  title =  "阿里镜像源仓库"
  href =   "https://opsx.alibaba.com/mirror"
  [[params.bookmark_link]]
  title =  "Kubernetes 官方站点"
  href =   "https://kubernetes.io/"
  [[params.bookmark_link]]
  title =  "ServiceMesh 社区站点"
  href =   "http://www.servicemesher.com/"
  [[params.bookmark_link]]
  title =  "Istio 官方站点"
  href =   "https://istio.io"
  
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 
